source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/plugins.zsh
source ~/.config/zsh/zconf.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/keys.zsh
source ~/.config/zsh/mappings.zsh
source ~/.config/zsh/completion.zsh

if [ -f ~/.sconfi/zsh/zshrc ]; then
  source ~/.sconfig/zsh/zshrc
fi

#autopair-init
#source ~/.zim/modules/fzf-tab/fzf-tab.plugin.zsh
source ~/.config/zsh/prompt.zsh
source ~/.config/zsh/functions/cd_git_root.zsh
